repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.81.0
  hooks:
    - id: terraform_fmt
    - id: terraform_checkov
    - id: terraform_providers_lock
    - id: terraform_tflint
    - id: terraform_tfsec
    - id: terraform_validate
