name: terraform-apply-main
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
env:
    TF_CLOUD_ORGANIZATION: "${{ vars.TF_CLOUD_ORGANIZATION }}"
    TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
    TF_WORKSPACE: "${{ vars.TF_WORKSPACE }}"
    CONFIG_DIRECTORY: "./"
jobs:
    deploy:
        runs-on: ubuntu-22.04
        name: "Terraform apply main pipeline"
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v3
              name: Checkout

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.20'
                check-latest: true
                cache: true
                cache-dependency-path: tests/go.sum

            - uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.0
                terraform_wrapper: false

            - name: Run integration tests
              working-directory: tests
              run: go mod tidy && go test -v -timeout 30m
              env:
                ATLAS_ORG_ID: ${{ vars.ATLAS_ORG_ID }}
                ATLAS_PROJECT_NAME: ${{ vars.ATLAS_PROJECT_NAME }}
                ATLAS_CLUSTER_NAME: ${{ vars.ATLAS_CLUSTER_NAME }}
                ATLAS_API_PUBLIC_KEY: ${{ secrets.ATLAS_API_PUBLIC_KEY }}
                ATLAS_API_PRIVATE_KEY: ${{ secrets.ATLAS_API_PRIVATE_KEY }}
                ATLAS_CLUSTER_PROVIDER_NAME: ${{ vars.ATLAS_CLUSTER_PROVIDER_NAME }}
                ATLAS_CLUSTER_BACKING_PROVIDER: ${{ vars.ATLAS_CLUSTER_BACKING_PROVIDER }}
                ATLAS_CLUSTER_REGION: ${{ vars.ATLAS_CLUSTER_REGION }}
                ATLAS_CLUSTER_VERSION: ${{ vars.ATLAS_CLUSTER_VERSION }}
                ATLAS_CLUSTER_SIZE_NAME: ${{ vars.ATLAS_CLUSTER_SIZE_NAME }}
                MONGO_DATABASE_NAME: ${{ vars.MONGO_DATABASE_NAME }}
                MONGO_DATABASE_ADMIN_USER: ${{ vars.MONGO_DATABASE_ADMIN_USER }}
                MONGO_DATABASE_ADMIN_PASSWORD: ${{ secrets.MONGO_DATABASE_ADMIN_PASSWORD }}
                MONGO_DATABASE_APP_USER: ${{ vars.MONGO_DATABASE_APP_USER }}
                MONGO_DATABASE_APP_PASSWORD: ${{ secrets.MONGO_DATABASE_APP_PASSWORD }}
                ATLAS_CLUSTER_CIDR: ${{ vars.ATLAS_CLUSTER_CIDR }}

            - name: Upload Configuration
              uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
              id: apply-upload
              with:
                workspace: ${{ env.TF_WORKSPACE }}
                directory: ${{ env.CONFIG_DIRECTORY }}
                
            - name: Create Apply Run
              uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
              id: apply-run
              with:
                workspace: ${{ env.TF_WORKSPACE }}
                configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

            - name: Apply
              uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
              if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
              id: apply
              with:
                run: ${{ steps.apply-run.outputs.run_id }}
                comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
